In [1]:
import pandas as pd
import numpy as np


In [2]:
df=pd.read_csv('Uncleaned_employees_final_dataset (1).csv')


In [3]:
df

employee_id         department     region  education gender  \
0             8724         Technology  region_26  Bachelors      m   
1            74430                 HR   region_4  Bachelors      f   
2            72255  Sales & Marketing  region_13  Bachelors      m   
3            38562        Procurement   region_2  Bachelors      f   
4            64486            Finance  region_29  Bachelors      m   
...            ...                ...        ...        ...    ...   
17412        64573         Technology   region_7  Bachelors      f   
17413        49584                 HR   region_7  Bachelors      m   
17414        49584                 HR   region_7  Bachelors      m   
17415        49584                 HR   region_7  Bachelors      m   
17416        64573                 HR   region_7  Bachelors      f   

      recruitment_channel  no_of_trainings  age  previous_year_rating  \
0                sourcing                1   24                   NaN   
1                   other                1   31                   3.0   
2                   other                1   31                   1.0   
3                   other                3   31                   2.0   
4                sourcing                1   30                   4.0   
...                   ...              ...  ...                   ...   
17412            referred                2   30                   5.0   
17413               other                1   33                   1.0   
17414               other                1   33                   1.0   
17415               other                1   33                   1.0   
17416            referred                1   35                   5.0   

       length_of_service  KPIs_met_more_than_80  awards_won  \
0                      1                      1           0   
1                      5                      0           0   
2                      4                      0           0   
3                      9                      0           0   
4                      7                      0           0   
...                  ...                    ...         ...   
17412                  6                      1           0   
17413                  9                      0           0   
17414                  9                      0           0   
17415                  9                      0           0   
17416                  4                      1           0   

       avg_training_score  
0                      77  
1                      51  
2                      47  
3                      65  
4                      61  
...                   ...  
17412                  81  
17413                  51  
17414                  51  
17415                  51  
17416                  81  

[17417 rows x 13 columns]

In [4]:
df["department"].unique()


array(['Technology', 'HR', 'Sales & Marketing', 'Procurement', 'Finance',
       'Analytics', 'Operations', 'Legal', 'R&D'], dtype=object)

In [5]:
df["region"].unique()   


array(['region_26', 'region_4', 'region_13', 'region_2', 'region_29',
       'region_7', 'region_22', 'region_16', 'region_17', 'region_24',
       'region_11', 'region_27', 'region_9', 'region_20', 'region_34',
       'region_23', 'region_8', 'region_14', 'region_31', 'region_19',
       'region_5', 'region_28', 'region_15', 'region_3', 'region_25',
       'region_12', 'region_21', 'region_30', 'region_10', 'region_33',
       'region_32', 'region_6', 'region_1', 'region_18'], dtype=object)

In [11]:
df["education"].dropna().unique()

array(['Bachelors', 'Masters & above', 'Below Secondary'], dtype=object)

In [8]:
df["education"].value_counts()

education
Bachelors          11519
Masters & above     4841
Below Secondary      286
Name: count, dtype: int64

In [12]:
df["gender"].unique()

array(['m', 'f'], dtype=object)

In [13]:
df["recruitment_channel"].unique()

array(['sourcing', 'other', 'referred'], dtype=object)

In [14]:
df["no_of_trainings"].unique()

array([1, 3, 2, 4, 5, 7, 6, 8, 9], dtype=int64)

In [15]:
df["age"].unique()

array([24, 31, 30, 36, 33, 51, 29, 40, 34, 37, 26, 49, 27, 25, 41, 52, 43,
       35, 42, 57, 46, 21, 32, 28, 38, 23, 58, 54, 44, 48, 45, 39, 59, 53,
       56, 47, 22, 20, 50, 55, 60], dtype=int64)

In [16]:
df["previous_year_rating"].unique()


array([nan,  3.,  1.,  2.,  4.,  5.])

In [20]:
df["previous_year_rating"].dropna().unique()

array([3., 1., 2., 4., 5.])

In [21]:
df["length_of_service"].unique()

array([ 1,  5,  4,  9,  7,  2,  3, 11, 12, 10,  6, 14, 18,  8, 26, 13, 22,
       19, 21, 15, 16, 17, 23, 20, 31, 24, 27, 28, 25, 29, 33, 30, 34, 32],
      dtype=int64)

In [25]:
df["KPIs_met_more_than_80"].unique()

array([1, 0], dtype=int64)

In [26]:
df["awards_won"].unique()

array([0, 1], dtype=int64)